// <auto-generated />
using System;
using Approval.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Approval.DAL.Migrations
{
    [DbContext(typeof(ApprovalDbContext))]
    partial class ApprovalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Approval.DAL.Entities.APStatus", b =>
                {
                    b.Property<int>("APStatusID")
                        .HasColumnType("integer")
                        .HasColumnName("apstatus_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APStatusID")
                        .HasName("pk_apstatus");

                    b.ToTable("apstatus");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalEmployeeFeedback", b =>
                {
                    b.Property<int>("APEmployeeFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("apemployee_feedback_id");

                    b.Property<int>("APFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("apfeedback_id");

                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("FeedbackLastResponseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_last_response_date");

                    b.Property<DateTime?>("FeedbackRequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_request_date");

                    b.Property<DateTime?>("FeedbackSubmitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_submit_date");

                    b.Property<bool>("IsAutoApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_approved");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsMultiProxy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_proxy");

                    b.Property<bool>("IsProxyEmployeeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy_employee_enabled");

                    b.Property<bool>("IsSCM")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scm");

                    b.Property<int?>("NFAApprovalSequenceType")
                        .HasColumnType("integer")
                        .HasColumnName("nfaapproval_sequence_type");

                    b.Property<string>("Particulars")
                        .HasColumnType("text")
                        .HasColumnName("particulars");

                    b.Property<int?>("ProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("proxy_employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SequenceNo")
                        .HasColumnType("numeric")
                        .HasColumnName("sequence_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APEmployeeFeedbackID")
                        .HasName("pk_approval_employee_feedback");

                    b.ToTable("approval_employee_feedback");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalEmployeeFeedbackRemarks", b =>
                {
                    b.Property<int>("APEmployeeFeedbackRemarksID")
                        .HasColumnType("integer")
                        .HasColumnName("apemployee_feedback_remarks_id");

                    b.Property<int>("APFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("apfeedback_id");

                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsProxyEmployeeRemarks")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy_employee_remarks");

                    b.Property<int?>("ProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("proxy_employee_id");

                    b.Property<string>("ProxyEmployeeRemarks")
                        .HasColumnType("text")
                        .HasColumnName("proxy_employee_remarks");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("RemarksDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remarks_date_time");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APEmployeeFeedbackRemarksID")
                        .HasName("pk_approval_employee_feedback_remarks");

                    b.ToTable("approval_employee_feedback_remarks");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalFeedback", b =>
                {
                    b.Property<int>("APFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("apfeedback_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HexColorCode")
                        .HasColumnType("text")
                        .HasColumnName("hex_color_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APFeedbackID")
                        .HasName("pk_approval_feedback");

                    b.ToTable("approval_feedback");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalForwardInfo", b =>
                {
                    b.Property<int>("APForwardInfoID")
                        .HasColumnType("integer")
                        .HasColumnName("apforward_info_id");

                    b.Property<string>("APEmployeeComment")
                        .HasColumnType("text")
                        .HasColumnName("apemployee_comment");

                    b.Property<string>("APForwardEmployeeComment")
                        .HasColumnType("text")
                        .HasColumnName("apforward_employee_comment");

                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<DateTime?>("CommentRequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comment_request_date");

                    b.Property<DateTime?>("CommentSubmitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comment_submit_date");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_feedback_id");

                    b.Property<int>("EmployeeFeedbackRemarksID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_feedback_remarks_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APForwardInfoID")
                        .HasName("pk_approval_forward_info");

                    b.ToTable("approval_forward_info");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalMultiProxyEmployeeInfo", b =>
                {
                    b.Property<long>("AMPEIID")
                        .HasColumnType("bigint")
                        .HasColumnName("ampeiid");

                    b.Property<int>("APEmployeeFeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("apemployee_feedback_id");

                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("AMPEIID")
                        .HasName("pk_approval_multi_proxy_employee_info");

                    b.ToTable("approval_multi_proxy_employee_info");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanel", b =>
                {
                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<int?>("APTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("aptype_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDynamicApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dynamic_approval");

                    b.Property<bool>("IsParallelApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parallel_approval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPanelID")
                        .HasName("pk_approval_panel");

                    b.ToTable("approval_panel");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanelEmployee", b =>
                {
                    b.Property<int>("APPanelEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_employee_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsMultiProxy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_proxy");

                    b.Property<bool>("IsProxyEmployeeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy_employee_enabled");

                    b.Property<bool>("IsSCM")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scm");

                    b.Property<int?>("NFAApprovalSequenceType")
                        .HasColumnType("integer")
                        .HasColumnName("nfaapproval_sequence_type");

                    b.Property<string>("Particulars")
                        .HasColumnType("text")
                        .HasColumnName("particulars");

                    b.Property<int?>("ProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("proxy_employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SequenceNo")
                        .HasColumnType("numeric")
                        .HasColumnName("sequence_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPanelEmployeeID")
                        .HasName("pk_approval_panel_employee");

                    b.ToTable("approval_panel_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanelEmployeeConfig", b =>
                {
                    b.Property<int>("APPEConfigID")
                        .HasColumnType("integer")
                        .HasColumnName("appeconfig_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsMultiProxy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_proxy");

                    b.Property<bool>("IsProxyEmployeeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy_employee_enabled");

                    b.Property<int?>("NFAApprovalSequenceType")
                        .HasColumnType("integer")
                        .HasColumnName("nfaapproval_sequence_type");

                    b.Property<int?>("ProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("proxy_employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SequenceNo")
                        .HasColumnType("numeric")
                        .HasColumnName("sequence_no");

                    b.Property<int?>("TemplateID")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPEConfigID")
                        .HasName("pk_approval_panel_employee_config");

                    b.ToTable("approval_panel_employee_config");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanelForwardEmployee", b =>
                {
                    b.Property<int>("APPanelForwardEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_forward_employee_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPanelForwardEmployeeID")
                        .HasName("pk_approval_panel_forward_employee");

                    b.ToTable("approval_panel_forward_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanelProxyEmployee", b =>
                {
                    b.Property<int>("APPanelProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_proxy_employee_id");

                    b.Property<int>("APPanelEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_employee_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPanelProxyEmployeeID")
                        .HasName("pk_approval_panel_proxy_employee");

                    b.ToTable("approval_panel_proxy_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalPanelProxyEmployeeConfig", b =>
                {
                    b.Property<int>("APPPECID")
                        .HasColumnType("integer")
                        .HasColumnName("apppecid");

                    b.Property<int>("APPEConfigID")
                        .HasColumnType("integer")
                        .HasColumnName("appeconfig_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APPPECID")
                        .HasName("pk_approval_panel_proxy_employee_config");

                    b.ToTable("approval_panel_proxy_employee_config");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalProcess", b =>
                {
                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<int>("APStatusID")
                        .HasColumnType("integer")
                        .HasColumnName("apstatus_id");

                    b.Property<int>("APTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("aptype_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ReferenceID")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("ApprovalProcessID")
                        .HasName("pk_approval_process");

                    b.ToTable("approval_process");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalProcessPanelMap", b =>
                {
                    b.Property<int>("ApprovalProcessPanelMapID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_panel_map_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<int>("ApprovalProcessID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_process_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("ApprovalProcessPanelMapID")
                        .HasName("pk_approval_process_panel_map");

                    b.ToTable("approval_process_panel_map");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ApprovalType", b =>
                {
                    b.Property<int>("APTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("aptype_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("APTypeID")
                        .HasName("pk_approval_type");

                    b.ToTable("approval_type");
                });

            modelBuilder.Entity("Approval.DAL.Entities.DOAApprovalPanelEmployee", b =>
                {
                    b.Property<long>("DOAApprovalPanelEmployeeID")
                        .HasColumnType("bigint")
                        .HasColumnName("doaapproval_panel_employee_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<long>("AssigneeEmployeeID")
                        .HasColumnType("bigint")
                        .HasColumnName("assignee_employee_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<long>("DOAMasterID")
                        .HasColumnType("bigint")
                        .HasColumnName("doamaster_id");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int>("TypeID")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("DOAApprovalPanelEmployeeID")
                        .HasName("pk_doaapproval_panel_employee");

                    b.ToTable("doaapproval_panel_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.DOAMaster", b =>
                {
                    b.Property<long>("DOAMasterID")
                        .HasColumnType("bigint")
                        .HasColumnName("doamaster_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("StatusID")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("DOAMasterID")
                        .HasName("pk_doamaster");

                    b.ToTable("doamaster");
                });

            modelBuilder.Entity("Approval.DAL.Entities.DocumentApprovalMaster", b =>
                {
                    b.Property<long>("DAMID")
                        .HasColumnType("bigint")
                        .HasColumnName("damid");

                    b.Property<int>("ApprovalStatusID")
                        .HasColumnType("integer")
                        .HasColumnName("approval_status_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("ExternalID")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("ReferenceKeyword")
                        .HasColumnType("text")
                        .HasColumnName("reference_keyword");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text")
                        .HasColumnName("reference_no");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("text")
                        .HasColumnName("template_body");

                    b.Property<int>("TemplateID")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("DAMID")
                        .HasName("pk_document_approval_master");

                    b.ToTable("document_approval_master");
                });

            modelBuilder.Entity("Approval.DAL.Entities.DocumentApprovalTemplate", b =>
                {
                    b.Property<long>("DATID")
                        .HasColumnType("bigint")
                        .HasColumnName("datid");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer")
                        .HasColumnName("category_type");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("DATName")
                        .HasColumnType("text")
                        .HasColumnName("datname");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("text")
                        .HasColumnName("template_body");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("DATID")
                        .HasName("pk_document_approval_template");

                    b.ToTable("document_approval_template");
                });

            modelBuilder.Entity("Approval.DAL.Entities.DynamicApprovalPanelEmployee", b =>
                {
                    b.Property<int>("DAPEID")
                        .HasColumnType("integer")
                        .HasColumnName("dapeid");

                    b.Property<string>("ApprovalPanels")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approval_panels");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("DepartmentIDs")
                        .HasColumnType("text")
                        .HasColumnName("department_ids");

                    b.Property<string>("DivisionIDs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("division_ids");

                    b.Property<string>("EmployeeIDs")
                        .HasColumnType("text")
                        .HasColumnName("employee_ids");

                    b.Property<string>("ExternalID")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<int>("HREmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("hremployee_id");

                    b.Property<string>("HRProxyEmployeeIDs")
                        .HasColumnType("text")
                        .HasColumnName("hrproxy_employee_ids");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("hierarchy_level");

                    b.Property<bool>("IncludeDepartmentHead")
                        .HasColumnType("boolean")
                        .HasColumnName("include_department_head");

                    b.Property<bool>("IncludeDivisionHead")
                        .HasColumnType("boolean")
                        .HasColumnName("include_division_head");

                    b.Property<bool>("IncludeHR")
                        .HasColumnType("boolean")
                        .HasColumnName("include_hr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxLimitAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("max_limit_amount");

                    b.Property<int>("MaximumJobGrade")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_job_grade");

                    b.Property<decimal>("MinLimitAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("min_limit_amount");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("DAPEID")
                        .HasName("pk_dynamic_approval_panel_employee");

                    b.ToTable("dynamic_approval_panel_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ManualApprovalPanelEmployee", b =>
                {
                    b.Property<long>("MAPPanelEmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mappanel_employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MAPPanelEmployeeID"));

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<int>("APTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("aptype_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsMultiProxy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_proxy");

                    b.Property<bool>("IsProxyEmployeeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy_employee_enabled");

                    b.Property<bool>("IsSCM")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scm");

                    b.Property<int?>("NFAApprovalSequenceType")
                        .HasColumnType("integer")
                        .HasColumnName("nfaapproval_sequence_type");

                    b.Property<int?>("ProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("proxy_employee_id");

                    b.Property<long>("ReferenceID")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SequenceNo")
                        .HasColumnType("numeric")
                        .HasColumnName("sequence_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("MAPPanelEmployeeID")
                        .HasName("pk_manual_approval_panel_employee");

                    b.ToTable("manual_approval_panel_employee");
                });

            modelBuilder.Entity("Approval.DAL.Entities.ManualApprovalPanelProxyEmployee", b =>
                {
                    b.Property<int>("MAPPanelProxyEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("mappanel_proxy_employee_id");

                    b.Property<int>("APPanelID")
                        .HasColumnType("integer")
                        .HasColumnName("appanel_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("MAPPanelEmployeeID")
                        .HasColumnType("integer")
                        .HasColumnName("mappanel_employee_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("MAPPanelProxyEmployeeID")
                        .HasName("pk_manual_approval_panel_proxy_employee");

                    b.ToTable("manual_approval_panel_proxy_employee");
                });

            modelBuilder.Entity("DAL.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditID"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_date");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_values");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("RowState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("row_state");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.HasKey("AuditID")
                        .HasName("pk_audit_log");

                    b.ToTable("audit_log");
                });
#pragma warning restore 612, 618
        }
    }
}
