using System;
using System.Data;
using System.Linq;
using System.Collections.Generic;
using System.Text.RegularExpressions;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Metadata;

using Core;
using Core.Extensions;
using Core.AppContexts;
using DAL.Core.Attribute;
using DAL.Core.Entities;
using System.Text;
using DAL.Core.EntityBase;
using System.ComponentModel;
using System.Data.SqlClient;
#if Npgsql
using Npgsql;
#endif
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using System.Diagnostics;

namespace DAL.Core
{
    public abstract class BaseDbContext : DbContext
    {
        protected BaseDbContext(DbContextOptions options) : base(options)
        {
            AppContexts.SetActiveDbContext(this);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            
            // Apply snake_case naming convention for PostgreSQL compatibility
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                // Convert table names to snake_case
                var tableName = entity.GetTableName();
                if (!string.IsNullOrEmpty(tableName))
                {
                    entity.SetTableName(ToSnakeCase(tableName));
                }

                // Convert column names to snake_case
                foreach (var property in entity.GetProperties())
                {
                    var columnName = property.GetColumnName();
                    if (!string.IsNullOrEmpty(columnName))
                    {
                        property.SetColumnName(ToSnakeCase(columnName));
                    }
                }

                // Convert key names to snake_case
                var key = entity.FindPrimaryKey();
                if (key != null)
                {
                    key.SetName(ToSnakeCase(key.GetName()));
                }

                // Convert foreign key constraint names to snake_case
                foreach (var foreignKey in entity.GetForeignKeys())
                {
                    foreignKey.SetConstraintName(ToSnakeCase(foreignKey.GetConstraintName()));
                }

                // Note: Index naming conversion skipped for EF Core 3.1 compatibility
                // Indexes will use default names generated by Npgsql
            }
        }

        private static string ToSnakeCase(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            // Insert an underscore between a letter and that letter + 1 lowercase letter / number
            // e.g., "CompanyTerms" -> "Company_Terms"
            var s1 = Regex.Replace(name, @"([a-z])([A-Z])", "$1_$2");
            
            // Insert an underscore between any number and a letter
            // e.g., "UserID123" -> "UserID_123"
            var s2 = Regex.Replace(s1, @"([0-9])([a-zA-Z])", "$1_$2");
            
            // Convert to lowercase
            return s2.ToLower();
        }

        public virtual DbSet<AuditLog> AuditLogs { get; set; }

        public override int SaveChanges()
        {
            return base.SaveChanges();
            //SaveChangesWithAudit();
            //return 0;
        }

        #region Audit Log
        public void SaveChangesWithAudit()
        {
            var auditEntries = OnBeforeSaveChanges();
            base.SaveChanges();
            OnAfterSaveChanges(auditEntries);
        }

        private List<AuditEntry> OnBeforeSaveChanges()
        {
            base.ChangeTracker.DetectChanges();

            var auditEntries = new List<AuditEntry>();
            foreach (var entry in base.ChangeTracker.Entries())
            {
                if (entry.Entity is AuditLog || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                    continue;

                var logProps = entry.Entity.GetType().GetProperties().Where(
                prop => System.Attribute.IsDefined(prop, typeof(LoggableAttribute))).ToList();

                if (logProps.Count.IsZero()) continue;

                var auditEntry = new AuditEntry(entry)
                {
                    TableName = entry.Metadata.GetTableName(),
                    RowState = entry.State.ToString()
                };

                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties)
                {
                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }

                    var propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    if (logProps.FirstOrDefault(p => p.Name == propertyName).IsNull()) continue;

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;

                        case EntityState.Deleted:
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;

                        case EntityState.Modified:
                            if (property.IsModified)
                            {
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                        case EntityState.Detached:
                            break;
                        case EntityState.Unchanged:
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                }
            }

            // Save audit entities that have all the modifications
            foreach (var auditEntry in auditEntries.Where(p => !p.HasTemporaryProperties))
            {
                AuditLogs.Add(auditEntry.ToAudit());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return auditEntries.Where(p => p.HasTemporaryProperties).ToList();
        }

        private void OnAfterSaveChanges(List<AuditEntry> auditEntries)
        {
            if (auditEntries.IsNull() || auditEntries.Count.IsZero()) return;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                AuditLogs.Add(auditEntry.ToAudit());
            }

            base.SaveChanges();
        }

        #endregion

        #region ExecuteScalar
        public object ExecuteScalar(string cmdText, params object[] parameters)
        {
            IsValidCommandText(cmdText);
            var command = Database.GetDbConnection().CreateCommand();
            if (Database.CurrentTransaction.IsNotNull())
            {
                command.Transaction = Database.CurrentTransaction.GetDbTransaction();
            }

            PrepareCommand(command, cmdText);
            PrepareCommandParameter(command, parameters);
            var value = command.ExecuteScalar();
            return value;
        }

        public object ExecuteScalarWithTransaction(string cmdText, params object[] parameters)
        {
            IsValidCommandText(cmdText);
            var command = Database.GetDbConnection().CreateCommand();
            if (Database.CurrentTransaction.IsNotNull())
            {
                command.Transaction = Database.CurrentTransaction.GetDbTransaction();
            }
            Database.OpenConnection();
            PrepareCommand(command, cmdText);
            PrepareCommandParameter(command, parameters);
            var value = command.ExecuteScalar();
            return value;
        }

        public object ExecuteReader(string cmdText, params object[] parameters)
        {
            IsValidCommandText(cmdText);
            var command = Database.GetDbConnection().CreateCommand();
            if (Database.CurrentTransaction.IsNotNull())
            {
                command.Transaction = Database.CurrentTransaction.GetDbTransaction();
            }

            PrepareCommand(command, cmdText);
            PrepareCommandParameter(command, parameters);
            var value = command.ExecuteReaderAsync();
            return value;
        }

        private void IsValidCommandText(string commandText)
        {
            if (commandText.IsNullOrEmpty()) throw new Exception("Query is blank.");
        }

        private void PrepareCommand(IDbCommand command, string cmdText)
        {
            command.CommandType = CommandType.Text;
            command.CommandText = cmdText;
        }

        protected void PrepareCommandParameter(IDbCommand command, object[] parameters)
        {
            if (parameters.IsNull() || parameters.Length.IsZero()) return;
            SetParameters(command, parameters);
        }

        protected void SetParameters(IDbCommand command, object[] parameterValues)
        {
            var parameters = new IDbDataParameter[parameterValues.Length];

            for (var i = 0; i < parameterValues.Length; i++)
            {
                var value = parameterValues[i];
                parameters[i] = command.CreateParameter();
                parameters[i].DbType = MappedDbType.GetDbType(value.GetType());
                parameters[i].ParameterName = i.ToString();
                parameters[i].Value = value;
                command.Parameters.Add(parameters[i]);
            }
        }

        #endregion

        #region Generic/Raw Query Execution
        public Dictionary<string, object> GetData(string query, bool pascalCase = false)
        {
            var fields = new List<string>();
            var dataRow = new Dictionary<string, object>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    if (reader.Read())
                    {
                        dataRow = GetDataDict(fields, reader, pascalCase);
                    }
                }

                Database.CloseConnection();
            }

            return dataRow;
        }

        public async Task<Dictionary<string, object>> GetDataAsync(string query, bool pascalCase = false)
        {
            var fields = new List<string>();
            var dataRow = new Dictionary<string, object>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                if (Database.CurrentTransaction.IsNotNull())
                {
                    command.Transaction = Database.CurrentTransaction.GetDbTransaction();
                }
                await Database.OpenConnectionAsync();

                using (var reader =await command.ExecuteReaderAsync())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    if (await reader.ReadAsync())
                    {
                        dataRow = GetDataDict(fields, reader, pascalCase);
                    }
                }

                await Database.CloseConnectionAsync();
            }

            return dataRow;
        }

        public Dictionary<string, object> GetDataDicWithTransaction(string query, bool pascalCase = false)
        {
            var fields = new List<string>();
            var dataRow = new Dictionary<string, object>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                if (Database.CurrentTransaction.IsNotNull())
                {
                    command.Transaction = Database.CurrentTransaction.GetDbTransaction();
                }
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    if (reader.Read())
                    {
                        dataRow = GetDataDict(fields, reader, pascalCase);
                    }
                }

                Database.CloseConnection();
            }

            return dataRow;
        }

        public IEnumerable<Dictionary<string, object>> GetDataDictCollection(string query)
        {
            
            var fields = new List<string>();
            var dataTable = new List<Dictionary<string, object>>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    while (reader.Read())
                    {
                        dataTable.Add(GetDataDict(fields, reader));
                    }
                }

                Database.CloseConnection();
            }

            return dataTable;
        }

        public IEnumerable<Dictionary<string, object>> GetDataDictCollectionWithTransaction(string query)
        {
            var fields = new List<string>();
            var dataTable = new List<Dictionary<string, object>>();


            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;

                if (Database.CurrentTransaction.IsNotNull())
                {
                    command.Transaction = Database.CurrentTransaction.GetDbTransaction();
                }
                Database.OpenConnection();


                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    while (reader.Read())
                    {
                        dataTable.Add(GetDataDict(fields, reader));
                    }
                }

                Database.CloseConnection();
            }

            return dataTable;
        }

        public async Task<IEnumerable<Dictionary<string, object>>> GetDataDictCollectionAsync(string query)
        {
            var fields = new List<string>();
            var dataTable = new List<Dictionary<string, object>>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                await Database.OpenConnectionAsync();

                using (var reader = await command.ExecuteReaderAsync())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        fields.Add(reader.GetName(i));
                    }

                    while (await reader.ReadAsync())
                    {
                        dataTable.Add(GetDataDict(fields, reader));
                    }
                }

                await Database.CloseConnectionAsync();
            }

            return dataTable;
        }

        public List<T> GetDataModelCollection<T>(string query)
        {
            var list = new List<T>();
            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var fields = GetFields(reader);
                        list.Add(CreateModel<T>(fields));
                    }
                }

                Database.CloseConnection();
            }

            return list;
        }

        public async Task<List<T>> GetDataModelCollectionAsync<T>(string query)
        {
            var list = new List<T>();
            try
            {
                using (var command = Database.GetDbConnection().CreateCommand())
                {

                    command.CommandTimeout = 600;
                    command.CommandText = query;

                    if (Database.CurrentTransaction.IsNotNull())
                    {
                        command.Transaction = Database.CurrentTransaction.GetDbTransaction();
                    }
                    await Database.OpenConnectionAsync();

                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            var fields = GetFields(reader);
                            list.Add(CreateModel<T>(fields));
                        }
                    }

                    await Database.CloseConnectionAsync();
                }
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
            

            return list;
        }

        public T GetModelData<T>(string query)
        {
            var model = Activator.CreateInstance<T>();
            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var fields = GetFields(reader);
                        model = CreateModel<T>(fields);
                        break;
                    }
                }

                Database.CloseConnection();
            }

            return model;
        }

        public async Task<T> GetModelDataAsync<T>(string query) 
        {
            var model = Activator.CreateInstance<T>();
            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                if (Database.CurrentTransaction.IsNotNull())
                {
                    command.Transaction = Database.CurrentTransaction.GetDbTransaction();
                }
                await Database.OpenConnectionAsync();

                using (var reader =await command.ExecuteReaderAsync())
                {
                    while (reader.Read())
                    {
                        var fields = GetFields(reader);
                        model = CreateModel<T>(fields);
                        break;
                    }
                }

                await Database.CloseConnectionAsync();
            }

            return model;
        }

        private static T CreateModel<T>(Dictionary<string, object> fields)
        {
            var model = Activator.CreateInstance<T>();
            var properties = TypeDescriptor.GetProperties(model);
            foreach (var field in fields)
            {
                var propInfo = properties.Find(field.Key, true);
                if (propInfo.IsNull() || propInfo.IsReadOnly) continue;
                var value = field.Value.MapField(propInfo.PropertyType);
                propInfo.SetValue(model, value);
            }
            var state = properties.Find("State", true);
            if (state.IsNotNull()) state.SetValue(model, ModelState.Unchanged);
            return model;
        }
        public string GetJsonData(string query)
        {
            var jsonResult = new StringBuilder();
            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = query;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    if (!reader.HasRows)
                    {
                        jsonResult.Append("[]");
                    }
                    else
                    {
                        while (reader.Read())
                        {
                            jsonResult.Append(reader.GetValue(0).ToString());
                        }
                    }
                }

                Database.CloseConnection();
                return jsonResult.ToString();
            }

        }
        #endregion

        #region Data Access Utilities
        private Dictionary<string, object> GetDataDict(IEnumerable<string> fields, IDataRecord reader, bool pascalCase = false)
        {
            var dataDict = new Dictionary<string, object>();

            foreach (var colName in fields)
            {
                var ordinal = reader.GetOrdinal(colName);
                var value = reader.GetValue(ordinal);
                var type = reader.GetDataTypeName(ordinal);

                var mappedFieldName = pascalCase ? colName.Substring(0, 1).ToLower() + colName.Substring(1, colName.Length - 2) + colName.Substring(colName.Length - 1, 1).ToLower() : colName;

                switch (type)
                {
                    case "bigint":
                        dataDict[mappedFieldName] = value.ToString();
                        break;
                    default:
                        dataDict[mappedFieldName] = value;
                        break;
                }
            }

            return dataDict;
        }

        #endregion

        #region Load GridModel

        private static readonly string[] listOfEscapeCharacters = new[] { "'" };

        internal string MakeSearchQuery(GridParameter parameters, string sql)
        {
            int offset = parameters.Offset * parameters.Limit;
            string[] searchByArray = Array.Empty<string>(),
                searchArray = Array.Empty<string>(),
                searchTypeArray = Array.Empty<string>();

            if (parameters.SearchBy.IsNotNullOrEmpty())
            {
                searchByArray = parameters.SearchBy.Split('$');
                if (parameters.Search.IsNull())
                {
                    for (int i = 0; i < searchByArray.Length; i++)
                    {
                        parameters.Search += '$';
                    }
                }

                searchArray = parameters.Search.Split('$');
                searchTypeArray = parameters.SearchType.IsNotNullOrEmpty() ? parameters.SearchType.Split('$') : string.Empty.Split('$');
            }

            var filter = string.Empty;
            if (parameters.SearchBy.IsNotNullOrEmpty() && parameters.Search.IsNotNullOrEmpty())
            {
                for (int i = 0; i < searchByArray.Length; i++)
                {
                    listOfEscapeCharacters.ToList().ForEach(character =>
                    {
                        searchArray[i] = searchArray[i].Replace(character, $"'{character}");
                    });

                    if (parameters.SearchType.IsNotNullOrEmpty())
                    {
                        if (searchTypeArray[i].Equals("date"))
                        {
                            string currentCulture = Util.SysDateFormat;
                            int currentCultureCode = 103;

                            switch (currentCulture)
                            {
                                case "dd/MM/yyyy":
                                    currentCultureCode = 103;
                                    break;
                                case "MM/dd/yyyy":
                                    currentCultureCode = 101;
                                    break;
                                case "yyyy/MM/dd":
                                    currentCultureCode = 111;
                                    break;
                                case "dd-MM-yyyy":
                                    currentCultureCode = 105;
                                    break;
                            }

                            filter += string.Format("CONVERT(VARCHAR, {0}, {2}) LIKE '%{1}%'", searchByArray[i], searchArray[i], currentCultureCode);
                        }
                        else
                        {
                            filter += $"{searchByArray[i]} LIKE '%{searchArray[i]}%'";
                        }
                    }
                    else
                    {
                        filter += $"{searchByArray[i]} LIKE '%{searchArray[i]}%'";
                    }

                    if (i + 1 < searchByArray.Length)
                    {
                        filter += " AND ";
                    }
                }

                filter = "WHERE " + filter;
            }

            var order = string.Empty;
            if (parameters.SortName.IsNotNullOrEmpty() && parameters.SortOrder.IsNotNullOrEmpty())
            {
                if (parameters.SortOrder.TrimStart('$').IsNotNullOrEmpty())
                {
                    var sortNameArray = parameters.SortName.Split('$');
                    var sortOrderArray = parameters.SortOrder.Split('$');

                    for (int i = 0; i < sortNameArray.Length; i++)
                    {
                        if (sortOrderArray[i].IsNullOrEmpty()) continue;
                        order += $"{sortNameArray[i]} {sortOrderArray[i]}" + ", ";
                    }

                    order = "ORDER BY " + order.TrimEnd(' ').TrimEnd(',');
                }
            }

            if (order.IsNullOrEmpty() && parameters.Sort.IsNotNullOrEmpty())
            {
                order = $"ORDER BY {parameters.Sort} {parameters.Order}";
            }

            if (parameters.ServerPagination)
            {
                return $@"WITH TAB
                        AS 
                        ( 
	                        SELECT ROW_NUMBER() OVER ({order} {string.Empty}) AS AutoGenRowNum, COUNT(*) OVER () AS TotalRows, TEMP.*
	                        FROM
	                        (

		                        {sql}

	                        ) TEMP

                            {filter}
                        )

                        SELECT * FROM TAB Where AutoGenRowNum > {offset} AND AutoGenRowNum <= {offset + parameters.Limit}";
            }

            return $@"SELECT * FROM ({sql}) AS TEMP {filter} {order}";
        }
        internal string MakeSearchQueryOptimized(GridParameter parameters, string sql)
        {
            int offset = parameters.Offset * parameters.Limit;
            string[] searchByArray = Array.Empty<string>(),
                searchArray = Array.Empty<string>(),
                searchTypeArray = Array.Empty<string>();

            if (parameters.SearchBy.IsNotNullOrEmpty())
            {
                searchByArray = parameters.SearchBy.Split('$');
                if (parameters.Search.IsNull())
                {
                    for (int i = 0; i < searchByArray.Length; i++)
                    {
                        parameters.Search += '$';
                    }
                }

                searchArray = parameters.Search.Split('$');
                searchTypeArray = parameters.SearchType.IsNotNullOrEmpty() ? parameters.SearchType.Split('$') : string.Empty.Split('$');
            }

            var filter = string.Empty;
            if (parameters.SearchBy.IsNotNullOrEmpty() && parameters.Search.IsNotNullOrEmpty())
            {
                for (int i = 0; i < searchByArray.Length; i++)
                {
                    listOfEscapeCharacters.ToList().ForEach(character =>
                    {
                        searchArray[i] = searchArray[i].Replace(character, $"'{character}");
                    });

                    if (parameters.SearchType.IsNotNullOrEmpty())
                    {
                        if (searchTypeArray[i].Equals("date"))
                        {
                            string currentCulture = Util.SysDateFormat;
                            int currentCultureCode = 103;

                            switch (currentCulture)
                            {
                                case "dd/MM/yyyy":
                                    currentCultureCode = 103;
                                    break;
                                case "MM/dd/yyyy":
                                    currentCultureCode = 101;
                                    break;
                                case "yyyy/MM/dd":
                                    currentCultureCode = 111;
                                    break;
                                case "dd-MM-yyyy":
                                    currentCultureCode = 105;
                                    break;
                            }

                            filter += string.Format("CONVERT(VARCHAR, {0}, {2}) LIKE '%{1}%'", searchByArray[i], searchArray[i], currentCultureCode);
                        }
                        else
                        {
                            filter += $"{searchByArray[i]} LIKE '%{searchArray[i]}%'";
                        }
                    }
                    else
                    {
                        filter += $"{searchByArray[i]} LIKE '%{searchArray[i]}%'";
                    }

                    if (i + 1 < searchByArray.Length)
                    {
                        filter += " AND ";
                    }
                }

                filter = "WHERE " + filter;
            }

            var order = string.Empty;
            if (parameters.SortName.IsNotNullOrEmpty() && parameters.SortOrder.IsNotNullOrEmpty())
            {
                if (parameters.SortOrder.TrimStart('$').IsNotNullOrEmpty())
                {
                    var sortNameArray = parameters.SortName.Split('$');
                    var sortOrderArray = parameters.SortOrder.Split('$');

                    for (int i = 0; i < sortNameArray.Length; i++)
                    {
                        if (sortOrderArray[i].IsNullOrEmpty()) continue;
                        order += $"{sortNameArray[i]} {sortOrderArray[i]}" + ", ";
                    }

                    order = "ORDER BY " + order.TrimEnd(' ').TrimEnd(',');
                }
            }

            if (order.IsNullOrEmpty() && parameters.Sort.IsNotNullOrEmpty())
            {
                order = $"ORDER BY {parameters.Sort} {parameters.Order}";
            }
            if (parameters.ServerPagination)
            {
                return $@"SELECT 
                            TEMP2.* 
                        FROM 
                            (SELECT ROW_NUMBER() OVER ({order} {string.Empty}) AS AutoGenRowNum, COUNT(*) OVER () AS TotalRows,TEMP.*
                              FROM
	                            (
                                   {sql}
                                ) TEMP
						      {filter}
                            ) TEMP2
                         WHERE AutoGenRowNum > {offset} AND AutoGenRowNum <=  {offset + parameters.Limit}
                        ";
            }

            return $@"SELECT * FROM ({sql}) AS TEMP {filter} {order}";
        }
        public GridModel LoadGridModel(GridParameter parameters, string commandText)
        {
            var gridModel = new GridModel();
            var list = new List<Dictionary<string, object>>();
            var cols = new List<string>();

            var totalRows = 0;

            commandText = MakeSearchQuery(parameters, commandText);


            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = commandText;
                Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        var name = reader.GetName(i);
                        if (//name != "AutoGenRowNum" && 
                            name != "TotalRows")
                        {
                            cols.Add(name);
                        }
                    }

                    //First Row
                    if (reader.Read())
                    {
                        if (parameters.ServerPagination) totalRows = Convert.ToInt32(reader["TotalRows"]);
                        list.Add(GetFields(cols, reader));
                    }
                    while (reader.Read())
                    {
                        list.Add(GetFields(cols, reader));
                    }

                }

                Database.CloseConnection();
            }

            gridModel.Rows = list;
            gridModel.Total = parameters.ServerPagination ? totalRows : list.Count;

            return gridModel;
        }
        public GridModel LoadGridModelOptimized(GridParameter parameters, string commandText)
        {
            var gridModel = new GridModel();
            var list = new List<Dictionary<string, object>>();
            var cols = new List<string>();

            var totalRows = 0;

            commandText = MakeSearchQueryOptimized(parameters, commandText);


            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = commandText;
                Database.OpenConnection();
                try
                {
                    using (var reader = command.ExecuteReader())
                    {
                        for (var i = 0; i < reader.FieldCount; i++)
                        {
                            var name = reader.GetName(i);
                            if (//name != "AutoGenRowNum" && 
                                name != "TotalRows")
                            {
                                cols.Add(name);
                            }
                        }

                        //First Row
                        if (reader.Read())
                        {
                            if (parameters.ServerPagination) totalRows = Convert.ToInt32(reader["TotalRows"]);
                            list.Add(GetFields(cols, reader));
                        }
                        while (reader.Read())
                        {
                            list.Add(GetFields(cols, reader));
                        }

                    }

                    Database.CloseConnection();
                }
                catch (Exception)
                {

                    Database.CloseConnection();
                }

            }

            gridModel.Rows = list;
            gridModel.Total = parameters.ServerPagination ? totalRows : list.Count;

            return gridModel;
        }

        public async Task<GridModel> LoadGridModelAsync(GridParameter parameters, string commandText)
        {
            var gridModel = new GridModel();
            var list = new List<Dictionary<string, object>>();
            var cols = new List<string>();

            var totalRows = 0;

            commandText = MakeSearchQuery(parameters, commandText);

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = commandText;
                await Database.OpenConnectionAsync();

                using (var reader = await command.ExecuteReaderAsync())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        var name = reader.GetName(i);
                        if (name != "TotalRows")
                        {
                            cols.Add(name);
                        }
                    }

                    //First Row
                    if (await reader.ReadAsync())
                    {
                        if (parameters.ServerPagination) totalRows = Convert.ToInt32(reader["TotalRows"]);
                        list.Add(GetFields(cols, reader));
                    }
                    while (await reader.ReadAsync())
                    {
                        list.Add(GetFields(cols, reader));
                    }
                }

                await Database.CloseConnectionAsync();
            }

            gridModel.Rows = list;
            gridModel.Total = parameters.ServerPagination ? totalRows : list.Count;

            return gridModel;
        }
        #endregion

        #region Load ComboModel
        public List<ComboModel> LoadComboModel(string commandText, string valueField)
        {
            return LoadComboModel(commandText, valueField, valueField);
        }

        public List<ComboModel> LoadComboModel(string commandText, string valueField, string textField)
        {
            return LoadComboModel(commandText, valueField, textField, string.Empty);
        }

        public List<ComboModel> LoadComboModel(string commandText, string valueField, string textField, string descField)
        {
            var comboList = new List<ComboModel>();
            var fields = new Dictionary<string, string>();

            using (var command = Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = commandText;

                Database.OpenConnection();
                using (var reader = command.ExecuteReader())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        var name = reader.GetName(i);

                        if (name.Equals(valueField, StringComparison.CurrentCultureIgnoreCase))
                        {
                            fields["ValueField"] = name;
                        }

                        if (name.Equals(textField, StringComparison.CurrentCultureIgnoreCase))
                        {
                            fields["TextField"] = name;
                        }

                        if (name.Equals(descField, StringComparison.CurrentCultureIgnoreCase))
                        {
                            fields["DescField"] = name;
                        }
                    }

                    while (reader.Read())
                    {
                        var combo = new ComboModel();
                        foreach (var field in fields.Values)
                        {
                            if (field.Equals(valueField, StringComparison.CurrentCultureIgnoreCase))
                            {
                                combo.value = (int)reader[field];
                            }

                            if (field.Equals(textField, StringComparison.CurrentCultureIgnoreCase))
                            {
                                combo.label = reader[field].ToString();
                            }

                            //if (field.Equals(descField, StringComparison.CurrentCultureIgnoreCase))
                            //{
                            //    combo.Desc = reader[field].ToString();
                            //}
                        }

                        comboList.Add(combo);
                    }
                }

                Database.CloseConnection();
            }

            return comboList;
        }

        #endregion

        #region Helper Methods
        private static Dictionary<string, object> GetFields(IDataRecord reader)
        {
            var fieldCount = reader.FieldCount;
            var fields = new Dictionary<string, object>(fieldCount);
            for (var i = 0; i < fieldCount; i++)
            {
                var fieldName = reader.GetName(i);
                var ordinal = reader.GetOrdinal(fieldName);
                fields[fieldName] = reader.GetValue(ordinal);
            }
            return fields;
        }
        private static Dictionary<string, object> GetFields(IEnumerable<string> cols, IDataRecord reader)
        {
            var values = new Dictionary<string, object>();
            foreach (var colName in cols)
            {
                var ordinal = reader.GetOrdinal(colName);
                var type = reader.GetDataTypeName(ordinal);
                var value = reader.GetValue(ordinal);

                if (value.IsNullOrDbNull())
                {
                    if (type == "nvarchar")
                    {
                        value = string.Empty;
                    }

                    values[colName] = value;
                    continue;
                }

                switch (type)
                {
                    case "bigint":
                        values[colName] = value.ToString();
                        break;
                    case "date":
                        values[colName] = ((DateTime)value).ToString(Util.SysDateFormat);
                        break;
                    case "datetime":
                        values[colName] = ((DateTime)value).ToString(Util.SysDateFormat + " " + Util.TimeFormat);
                        break;
                    case "time":
                        values[colName] = DateTime.MinValue.Add((TimeSpan)value).ToString(Util.TimeFormat);
                        break;
                    default:
                        values[colName] = value;
                        break;
                }
            }

            return values;
        }

        #endregion

        #region Bulk Upload
        public bool BulkInsertFromDataTableToMSSQL(string tableName, DataTable dataTable, bool isTruncateTable, string[] DbColumnName, string[] InputColumnName)
        {

            if (DbColumnName.Length != InputColumnName.Length)
                return false;

            using (SqlConnection connection = new SqlConnection(Database.GetDbConnection().ConnectionString))
            {
                connection.Open();
                if (isTruncateTable)
                {
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandText = $"truncate table {tableName}";
                        command.Parameters.Clear();
                        command.ExecuteNonQuery();
                    }
                }

                using (SqlBulkCopy bulkCopy = new SqlBulkCopy(connection))
                {
                    bulkCopy.DestinationTableName = tableName;

                    try
                    {
                        for (int i = 0; i < DbColumnName.Length; i++)
                        {
                            bulkCopy.ColumnMappings.Add(InputColumnName[i], DbColumnName[i]);
                        }

                        bulkCopy.WriteToServer(dataTable);
                        Console.WriteLine("Bulk insert completed.");
                        return true;
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Error: " + ex.Message);
                        return false;
                    }
                }
            }
        }

        public bool BulkInsertFromDataTableToPostgreSQL(string tableName, DataTable dataTable, bool isTruncateTable, string[] dbColumnName, string[] inputColumnName)
        {
            if (dbColumnName.Length != inputColumnName.Length)
                return false;

            var connection = Database.GetDbConnection();
            var wasOpen = connection.State == System.Data.ConnectionState.Open;

            try
            {
                if (!wasOpen)
                {
                    Database.OpenConnection();
                }

                if (isTruncateTable)
                {
                    using (var command = connection.CreateCommand())
                    {
                        command.CommandText = $"TRUNCATE TABLE {tableName} RESTART IDENTITY CASCADE";
                        command.ExecuteNonQuery();
                    }
                }

                using (var transaction = connection.BeginTransaction())
                {
                    foreach (DataRow row in dataTable.Rows)
                    {
                        using (var command = connection.CreateCommand())
                        {
                            command.Transaction = transaction;
                            var columnNames = new List<string>();
                            var parameterNames = new List<string>();

                            for (int i = 0; i < dbColumnName.Length; i++)
                            {
                                columnNames.Add(dbColumnName[i]);
                                parameterNames.Add($":p{i}");
                                var parameter = command.CreateParameter();
                                parameter.ParameterName = $"p{i}";
                                parameter.Value = row[inputColumnName[i]] ?? DBNull.Value;
                                command.Parameters.Add(parameter);
                            }

                            command.CommandText = $"INSERT INTO {tableName} ({string.Join(", ", columnNames)}) VALUES ({string.Join(", ", parameterNames)})";
                            command.ExecuteNonQuery();
                        }
                    }

                    transaction.Commit();
                }

                Console.WriteLine("Bulk insert completed.");
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
                return false;
            }
            finally
            {
                if (!wasOpen)
                {
                    Database.CloseConnection();
                }
            }
        }

        public bool ExecuteSQLCommand(string sql)
        {
            try
            {
                var cmd = Database.GetDbConnection().CreateCommand();
                if (Database.CurrentTransaction.IsNotNull())
                {
                    cmd.Transaction = Database.CurrentTransaction.GetDbTransaction();
                }
                Database.OpenConnection();
                cmd.CommandText = sql;
                cmd.Parameters.Clear();
                var value = cmd.ExecuteNonQuery();

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
        #endregion
    }
}
