// <auto-generated />
using System;
using Mail.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mail.DAL.Migrations
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditID"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_date");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_values");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("RowState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("row_state");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.HasKey("AuditID")
                        .HasName("pk_audit_log");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Mail.DAL.Entities.MailConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_name");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_ssl");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SeqNo")
                        .HasColumnType("numeric")
                        .HasColumnName("seq_no");

                    b.Property<int>("SleepTime")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_time");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("ConfigId")
                        .HasName("pk_mail_configuration");

                    b.ToTable("mail_configuration");
                });

            modelBuilder.Entity("Mail.DAL.Entities.MailGroupSetup", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text")
                        .HasColumnName("attachment_path");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<string>("IntervalOn")
                        .HasColumnType("text")
                        .HasColumnName("interval_on");

                    b.Property<decimal>("IntervalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("interval_value");

                    b.Property<bool>("IsFromInterface")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_interface");

                    b.Property<DateTime?>("MailGenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mail_gen_time");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReportGenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_gen_time");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("integer")
                        .HasColumnName("sensitivity");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("GroupId")
                        .HasName("pk_mail_group_setup");

                    b.ToTable("mail_group_setup");
                });

            modelBuilder.Entity("Mail.DAL.Entities.MailSetup", b =>
                {
                    b.Property<int>("MailId")
                        .HasColumnType("integer")
                        .HasColumnName("mail_id");

                    b.Property<string>("CompanyID")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("text")
                        .HasColumnName("created_ip");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<short>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint")
                        .HasColumnName("row_version");

                    b.Property<string>("To_CC_BCC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_cc_bcc");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("text")
                        .HasColumnName("updated_ip");

                    b.HasKey("MailId")
                        .HasName("pk_mail_setup");

                    b.ToTable("mail_setup");
                });
#pragma warning restore 612, 618
        }
    }
}
